[package]
name = "GrpcExperimentation"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic = "0.14"
tokio = { version = "1", features = ["full"] }
prost = "0.14.1"
tonic-prost = "0.14"
tonic-reflection = "0.14.0"

[build-dependencies]
tonic-prost-build = "0.14"
tonic-build = "0.14.2"
